name: emoji_lumberdash
description: Lumberdash package that colors your logs adds emoji's for more visual clarity.
version: 1.0.0
homepage: https://github.com/fabiancrx/emoji_lumberdash
author: Fabian Quintanar <croxx5f@protonmail.com>


environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  lumberdash: ^2.1.0
  meta: ^1.0.0
  ansicolor: ^1.0.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
