name: emoji_lumberdash
description: Customizable lumberdash client that colors your logs and adds emoji's for more visual clarity.
version: 2.0.0
homepage: https://github.com/fabiancrx/emoji_lumberdash


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  lumberdash: ^3.0.0
  ansicolor: ^2.0.1

dev_dependencies:
  test: ^1.16.8
